stages:
  - Test
  - Release

#
# Tests
#

Prove:
  stage: Test
  except:
    - master
  image: registry.gitlab.com/tyil/docker-perl6:debian-dev-latest
  variables:
    ASSIXT_TESTING_SILENT: "1"
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - /usr/local/share/perl6/site
  before_script:
    - apt update
    - apt install -y build-essential
    - zef install App::Prove6
    - zef install --deps-only --test-depends --/test .
  script: prove6 -l

RakuDist:
  stage: Test
  image: alpine
  before_script:
    - apk add --no-cache curl
  script:
    - curl -d thing="$CI_PROJECT_URL" -d sha="$CI_COMMIT_SHA" https://rakudist.raku.org/queue

#
# Release targets
#

Distribution:
  stage: Release
  only:
    refs:
      - tags
      - master
  image: rakudo-star
  script:
    - echo "NOOP"
  artifacts:
    name: App-CPAN-${CI_COMMIT_TAG}
    paths:
      - META6.json
      - lib
      - bin
      - t
      - resources
